version: "3.9"
services:
  db:
    container_name: db_pg
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cism
      POSTGRES_PASSWORD: 321678
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5434:5432"






  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

