# Generated by Django 4.1 on 2023-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
                ('is_available', models.BooleanField(default=True, verbose_name='доступный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='дата и время изменения')),
                ('status', models.CharField(choices=[('created', 'created'), ('started', 'started'), ('finished', 'finished')], default='created', max_length=10, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Рабочая задача',
                'verbose_name_plural': 'Рабочая задача',
            },
        ),
    ]
