# Generated by Django 4.1 on 2023-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
